### ISSUE TITLE
Love this project so much

### ISSUE THREAD

**Issue by dorianmariefr** [davidwessman/syntax_tree-erb#47]
I was already a big fan of syntax tree but this is awesome. BTW how hard is it to support slim and Hank and jbuilder?

**Comment by davidwessman** [comment]
> I was already a big fan of syntax tree but this is awesome. BTW how hard is it to support slim and Hank and jbuilder?

I missed this issue! Cool 😊

It depends, but check out some of the examples in the syntax_tree-repo. I based this one on the XML-one.

**Comment by dorianmariefr** [comment]
@davidwessman Thanks <3
